name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build Tool
      run: dotnet build ./Tool/QuickVaultTool --configuration Release --no-restore
    - name: Build Sample.WebSite.Core
      run: dotnet build ./Samples/QuickVault.Sample.WebSite.Core --configuration Release --no-restore
    - name: Test
      run: dotnet test ./Test/QuickVault.IntegrationTests --no-restore --verbosity normal
