name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: Install dependencies
      run: dotnet restore
    - name: Build Tool
      run: dotnet build ./Tool/QuickVaultTool --configuration Release --no-restore
    - name: Build Sample.WebSite.Core
      run: dotnet build ./Samples/QuickVault.Sample.WebSite.Core --configuration Release --no-restore
    - name: Test
      run: dotnet test ./Test/QuickVault.IntegrationTests --no-restore --verbosity normal
    - name: Publish QuickVault on version change
      uses: rohith/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/QuickVault/QuickVault.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        VERSION_FILE_PATH: Directory.Build.props
    - name: Publish QuickVault.Configuration.Core on version change
      uses: rohith/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/QuickVault.Configuration.Core/QuickVault.Configuration.Core.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        VERSION_FILE_PATH: Directory.Build.props
